apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helloworld-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-staging.yaml
    path: manifests/Helm_exercise
    repoURL: https://github.com/kapekost/nd064_course_1
    targetRevision: HEAD
