apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginx-helloworld-service
  namespace: {{ .Values.namespace.name }} 
spec:
  selector:
    app: nginx-helloworld
  ports:
    - protocol: TCP
      type: {{ .Values.service.type }} 
      port:  {{ .Values.service.port }} 
